name: Notebook

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [ opened, synchronize, reopened, edited ]
    #trigger this workflow if files have changed in notebook
    paths:
      - "src/notebook/**"

permissions:
  contents: read

jobs:
  build-notebook:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/notebook
    steps:
      - uses: actions/checkout@v5
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.17"
          enable-cache: true
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "./src/notebook/.python-version"
      - name: Install the project
        run: uv sync --locked --all-extras --dev
